[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.7"
tokio = { version = "1", features = ["full"] }
is_prime = "2.0.9"
rand = "0.8.5"
log = "0.4.22"
env_logger = "0.11.3"